"""PreToolUse guard — a deterministic safety net for destructive tool calls.

Classifies a pending Bash/Edit/Write/MultiEdit into a risk tier and tells Claude Code to
**deny** (block) or **ask** (confirm) before it runs; low-risk calls emit nothing and fall
through to the normal permission flow. Ported from fann-core's permissions model. Pure
Python, cross-platform, no third-party deps.

Tiers:
  deny  — writing a secret file (.env*, *.pem/*.key, **/secrets/**, credentials, .git internals)
          or a catastrophic shell command (rm -rf / ~ /* $HOME / drive-root, find -delete from root,
          fork bomb, dd to a device, mkfs, recursive chmod 777 on root). Blocked outright.
  ask   — consequential-but-legit: lockfile / CI-workflow writes; rm -rf <path>, find -delete,
          git force-push / reset --hard / clean -f / history rewrite, DB drop, package publish,
          piping a download into a shell. The user confirms. (Routine config like package.json/
          tsconfig is NOT gated — frequent and not dangerous; over-prompting gets the guard disabled.)
  allow — everything else; the hook stays silent so normal handling applies.

Escape hatch: `.claudster/config.toml [guard] allow = ["substr", ...]` may only DOWNGRADE an `ask`
to `allow` (it can never override a `deny`); it matches the command/path value. Use specific strings.

Kill switch: for users who run Claude Code with `bypassPermissions` and want zero additional
gating from claudster, the guard can be turned off entirely (bypasses ALL tiers, deny included) via:
  * env var `CLAUDSTER_GUARD_DISABLED=1` (also 1/true/yes/on) — global, survives plugin updates.
  * `.claudster/config.toml [guard] enabled = false`  (or `mode = "off"`) — per-repo or user-level.
When disabled, the hook exits 0 immediately and every call falls through to normal permission handling.
"""
from __future__ import annotations

import json
import os
import re
import sys

# ── protected-path rules (write → deny) ──────────────────────────────────────
_SECRET_BASENAMES = {"id_rsa", "id_dsa", "id_ecdsa", "id_ed25519", "credentials",
                     ".npmrc", ".pypirc", ".netrc", ".pgpass", ".htpasswd"}
_SECRET_SUFFIXES = (".pem", ".key", ".p12", ".pfx", ".keystore", ".jks")
_ENV_RE = re.compile(r"(^|/)\.env(\.|$)", re.I)
_ENV_EXAMPLE_RE = re.compile(r"\.env\.(example|sample|template|dist)$", re.I)

# Lockfiles are normally regenerated by the package manager, so a hand-edit is unusual enough to
# confirm. Routine manifests (package.json/tsconfig) are deliberately NOT gated — too frequent, not risky.
_ASK_BASENAMES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "cargo.lock",
                  "uv.lock", "composer.lock", "gemfile.lock"}
_CI_WORKFLOW_RE = re.compile(r"(^|/)(\.github|\.gitea)/workflows/", re.I)


def classify_write(file_path: str) -> tuple[str, str]:
    """Risk tier (deny|ask|allow) + reason for writing/editing ``file_path``."""
    p = file_path.replace("\\", "/")
    parts = [seg.lower() for seg in p.split("/") if seg]
    base = parts[-1] if parts else ""

    if any(seg in ("secrets", ".secrets") for seg in parts):
        return "deny", f"writes into a secrets directory ({base})"
    if ".git" in parts[:-1]:
        return "deny", "writes into the .git internal directory"
    if _ENV_RE.search(p) and not _ENV_EXAMPLE_RE.search(p):
        return "deny", f"writes an environment/secret file ({base})"
    if base in _SECRET_BASENAMES or any(base.endswith(s) for s in _SECRET_SUFFIXES):
        return "deny", f"writes a credential/key file ({base})"

    if base in _ASK_BASENAMES:
        return "ask", f"edits a lockfile ({base})"
    if _CI_WORKFLOW_RE.search(p):
        return "ask", "edits a CI/CD workflow"
    return "allow", ""


# ── bash rules ───────────────────────────────────────────────────────────────
# Catastrophic delete targets: a filesystem/home root or a *bare* drive root (C:\ ), NOT a drive
# subpath (E:\proj\dist falls through to ask).
_CATASTROPHIC_TARGET = re.compile(
    r"--no-preserve-root"
    r"|(?:^|\s)(?:/|/\*|~/|~|\$\{?HOME\}?)(?:\s|$|;|&|\|)"
    r"|(?:^|\s)[A-Za-z]:[\\/]?(?:\s|$|;|&|\|)",
    re.I,
)
_FORK_BOMB = re.compile(r":\(\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:")


def _strip_quotes(s: str) -> str:
    """Drop quotes so quoted flags/targets still match (rm '-rf' \"/\" → rm -rf /)."""
    return s.replace('"', "").replace("'", "")


def _has_flag(cmd: str, letter: str, longname: str) -> bool:
    """True if `cmd` carries the short flag (e.g. -rf / -r) or the long flag (--recursive)."""
    return bool(re.search(rf"(?:^|\s)-\w*{letter}\w*\b", cmd, re.I)) or longname in cmd.lower()


def _is_rm_recursive_force(cmd: str) -> bool:
    if not re.search(r"\brm\b", cmd):
        return False
    return _has_flag(cmd, "r", "--recursive") and _has_flag(cmd, "f", "--force")


def _is_win_recursive_delete(cmd: str) -> bool:
    """Native Windows recursive delete — the POSIX ``rm`` path is handled by _is_rm_recursive_force.

    Catches PowerShell ``Remove-Item -Recurse -Force`` (and the Remove-Item aliases ri/rmdir/rd/del/
    erase) plus cmd.exe ``rmdir``/``rd``/``del``/``erase`` with the ``/s`` recurse-subdirectories switch.
    This is a Windows-primary environment, so these are the real footguns the POSIX rules miss."""
    if not re.search(r"(?:^|[\s;&|(])(?:remove-item|ri|rmdir|rd|del|erase)\b", cmd, re.I):
        return False
    ps_recurse_force = bool(re.search(r"(?:^|\s)-rec\w*", cmd, re.I)) and bool(re.search(r"(?:^|\s)-for\w*", cmd, re.I))
    cmd_slash_s = bool(re.search(r"(?:^|\s)/s\b", cmd, re.I))
    return ps_recurse_force or cmd_slash_s


def classify_bash(command: str) -> tuple[str, str]:
    """Risk tier (deny|ask|allow) + reason for a shell command."""
    c = command.strip()
    cl = c.lower()
    n = _strip_quotes(c)          # quote-normalized: defeats `rm '-rf' "/"` evasion
    nl = n.lower()
    rm_rf = _is_rm_recursive_force(n)
    catastrophic = bool(_CATASTROPHIC_TARGET.search(n))
    find_delete = bool(re.search(r"\bfind\b.*?(?:-delete\b|-exec\s+rm\b)", nl))
    win_del = _is_win_recursive_delete(n)

    # ── deny: catastrophic ──
    if rm_rf and catastrophic:
        return "deny", "recursive force-delete of a root/home path (rm -rf)"
    if find_delete and catastrophic:
        return "deny", "find -delete from a root/home path"
    if win_del and catastrophic:
        return "deny", "recursive force-delete of a root/home path (Windows Remove-Item/rmdir)"
    if re.search(r"\brmtree\s*\(\s*['\"]?(?:/|~|[A-Za-z]:\\?)['\"]?\s*\)", c, re.I):
        return "deny", "recursive tree delete of a root/home path (rmtree)"
    if _FORK_BOMB.search(c):
        return "deny", "fork bomb"
    if re.search(r"\bdd\b.*\bof=/dev/", nl) or re.search(r"\bmkfs", nl) or re.search(r">\s*/dev/sd[a-z]", nl):
        return "deny", "writes directly to a disk device"
    if (re.search(r"\bchmod\b", nl) and _has_flag(n, "r", "--recursive")
            and re.search(r"\b0?777\b", nl) and catastrophic):
        return "deny", "recursive chmod 777 on a root path"

    # ── ask: destructive-but-legit ──
    if rm_rf:
        return "ask", "recursive force-delete (rm -rf)"
    if find_delete:
        return "ask", "find with -delete / -exec rm"
    if win_del:
        return "ask", "recursive delete (Windows Remove-Item -Recurse / rmdir /s)"
    # git rules tolerate intervening options (e.g. `git -c k=v push --force`) but stay within one
    # command segment (the [^;&|]* won't cross a ; && || into an unrelated command). The trailing
    # `+\S` catches a force-push via refspec (`git push origin +main`), not just the --force flags.
    if re.search(r"\bgit\b[^;&|]*\bpush\b[^;&|]*(--force\b|--force-with-lease\b|(?:^|\s)-f\b|(?:^|\s)\+\S)", c):
        return "ask", "git force-push"
    if re.search(r"\bgit\b[^;&|]*\breset\s+--hard\b", c):
        return "ask", "git reset --hard"
    if re.search(r"\bgit\b[^;&|]*\bclean\b[^;&|]*(?:^|\s)-\w*f", c):
        return "ask", "git clean (force)"
    if re.search(r"\bgit\b[^;&|]*\bfilter-(repo|branch)\b", c):
        return "ask", "git history rewrite"
    if re.search(r"\b(drop\s+(table|database|schema)|truncate\s+table)\b", cl):
        return "ask", "destructive SQL (drop/truncate)"
    if re.search(r"\b(npm|yarn|pnpm)\s+publish\b|\btwine\s+upload\b|\bcargo\s+publish\b", cl):
        return "ask", "publishing a package"
    if re.search(r"\b(curl|wget|iwr|invoke-webrequest)\b[^|]*\|\s*(sudo\s+)?(sh|bash|zsh|iex|python)\b", cl):
        return "ask", "piping a download into a shell"
    return "allow", ""


def decide(tool_name: str, tool_input, allow_patterns: list[str]) -> tuple[str, str]:
    """Top-level decision. Classify FIRST; the allow escape hatch may only DOWNGRADE an `ask` to
    `allow` (never override a `deny`), and it matches the command/path value — not the JSON envelope —
    so a key name like "command" can't disable the guard. Never raises on a malformed payload."""
    if not isinstance(tool_input, dict):
        return "allow", ""

    if tool_name in ("Write", "Edit", "MultiEdit"):
        target = str(tool_input.get("file_path") or tool_input.get("path") or "")
        tier, reason = classify_write(target) if target else ("allow", "")
    elif tool_name == "Bash":
        target = str(tool_input.get("command", ""))
        tier, reason = classify_bash(target)
    else:
        return "allow", ""

    if tier == "ask" and any(pat and pat.lower() in target.lower() for pat in allow_patterns):
        return "allow", ""
    return tier, reason


# ── hook I/O glue ────────────────────────────────────────────────────────────
_TRUTHY = {"1", "true", "yes", "on"}


def _load_guard_config(root: str) -> dict:
    """Parse the ``[guard]`` table from ``<root>/.claudster/config.toml``; {} on any problem."""
    cfg = os.path.join(root, ".claudster", "config.toml")
    if not os.path.isfile(cfg):
        return {}
    try:
        import tomllib
        with open(cfg, "rb") as fh:
            data = tomllib.load(fh)
        section = data.get("guard", {})
        return section if isinstance(section, dict) else {}
    except Exception:
        return {}


def _load_allow(root: str) -> list[str]:
    allow = _load_guard_config(root).get("allow", [])
    return [str(x) for x in allow] if isinstance(allow, list) else []


def guard_disabled(root: str) -> bool:
    """True when the guard is turned off entirely (all tiers bypassed).

    Precedence: the env var wins (global, survives plugin auto-updates); otherwise the per-repo
    `[guard]` table — `enabled = false` or `mode = "off"`. Any parse problem → not disabled (fail safe)."""
    if os.environ.get("CLAUDSTER_GUARD_DISABLED", "").strip().lower() in _TRUTHY:
        return True
    section = _load_guard_config(root)
    if section.get("enabled") is False:
        return True
    if str(section.get("mode", "")).strip().lower() == "off":
        return True
    return False


def main() -> None:
    _reconfig = getattr(sys.stdout, "reconfigure", None)
    if _reconfig:
        try:
            _reconfig(encoding="utf-8")
        except Exception:
            pass
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)  # never block on a malformed payload

    try:
        tool_name = data.get("tool_name", "")
        tool_input = data.get("tool_input", {})
        root = data.get("cwd") or os.getcwd()
        if guard_disabled(root):
            sys.exit(0)  # kill switch: bypass every tier, defer to normal permission handling
        tier, reason = decide(tool_name, tool_input, _load_allow(root))
    except Exception:
        sys.exit(0)  # any unexpected shape → fail open, never crash the tool call

    if tier in ("deny", "ask"):
        tail = (" Blocked as too dangerous to run automatically — do it by hand if you are certain."
                if tier == "deny" else " Confirm only if this is intended.")
        out = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": tier,
                "permissionDecisionReason": f"[claudster guard] {reason}.{tail}",
            }
        }
        print(json.dumps(out))
    sys.exit(0)


if __name__ == "__main__":
    main()
